version: '3'
services:
  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: acme_traders